services:
  grading-server-app-1:
    container_name: grading-server-app-1
    # build: .
    ports:
      - "18081:8080"
    image: tollea1234/grading-server-app:${version}
    restart: always
    deploy:
      resources:
        limits:
          memory: '512m'